# Generated by Django 5.0.6 on 2024-05-18 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(blank=True, max_length=150, null=True, verbose_name="Место")),
                ("execution_time", models.DateTimeField(verbose_name="Дата выполнение")),
                ("action", models.CharField(max_length=150, verbose_name="Действие")),
                ("execution_duration_seconds", models.IntegerField(verbose_name="Время выполнения (в секундах)")),
                ("award", models.CharField(blank=True, max_length=150, null=True, verbose_name="Вознаграждение")),
                ("periodicity", models.CharField(default=1, max_length=20, verbose_name="Периодичность")),
                ("is_useful", models.BooleanField(default="False", verbose_name="Полезность")),
                ("is_shared", models.BooleanField(default="False", verbose_name="Публичность")),
                ("picture", models.ImageField(blank=True, null=True, upload_to="pictures/", verbose_name="Картинка")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
