# Generated by Django 5.0.6 on 2024-05-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.DateTimeField(verbose_name="Дата выполнения"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.SmallIntegerField(default=1, verbose_name="Периодичность в неделю"),
        ),
    ]
