# Generated by Django 5.0.6 on 2024-05-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0002_alter_habit_execution_time_alter_habit_periodicity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="is_useful",
        ),
        migrations.AddField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(default="False", verbose_name="Приятность"),
        ),
    ]
