# Generated by Django 5.0.6 on 2024-05-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0005_alter_habit_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(default=False, verbose_name="Приятность"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_shared",
            field=models.BooleanField(default=False, verbose_name="Публичность"),
        ),
    ]
