# Generated by Django 5.0.6 on 2024-05-18 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0006_alter_habit_is_pleasant_alter_habit_is_shared"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="connected_habits",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET,
                related_name="useful_habits",
                to="habbits.habit",
                verbose_name="Приятные привычки",
            ),
        ),
    ]
