# Generated by Django 5.0.6 on 2024-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0007_habit_connected_habits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.TimeField(verbose_name="Дата выполнения"),
        ),
    ]
