# Generated by Django 5.0.6 on 2024-05-19 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0008_alter_habit_execution_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="connected_habits",
        ),
        migrations.AddField(
            model_name="habit",
            name="connected_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET,
                related_name="useful_habit",
                to="habbits.habit",
                verbose_name="Приятная привычка",
            ),
        ),
    ]
