# Generated by Django 5.0.6 on 2024-05-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0009_remove_habit_connected_habits_habit_connected_habit"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="execution_date",
            field=models.DateField(default="2024-05-21", verbose_name="Дата начала выполнения привычки"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.TimeField(verbose_name="Время выполнения"),
        ),
    ]
