# Generated by Django 5.0.6 on 2024-05-21 15:44

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0011_alter_habit_execution_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="execution_date",
            field=models.DateField(default=datetime.date(2024, 5, 22), verbose_name="Дата начала выполнения привычки"),
        ),
    ]
