# Generated by Django 5.0.6 on 2024-05-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0012_alter_habit_execution_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.SmallIntegerField(default=7, verbose_name="Периодичность в неделю"),
        ),
    ]
