# Generated by Django 5.0.6 on 2024-06-07 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0014_alter_habit_execution_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="execution_date",
            field=models.DateField(default=datetime.date(2024, 6, 8), verbose_name="Дата начала выполнения привычки"),
        ),
    ]
